services:
  # FastAPI Server
  - type: web
    name: retrieval-plugin-server 
    region: oregon
    plan: starter
    env: docker
    dockerfilePath: ./Dockerfile
    envVars: 
      - key: DATASTORE
        value: weaviate
      - key: BEARER_TOKEN
        generateValue: true
        
      - key: OPENAI_API_KEY
        sync: false
      - key: WEAVIATE_URL
        value: https://my-first-sandbox-cluster-7w2unjhy.weaviate.network
      - key: WEAVIATE_API_KEY
        value: ISmXZCkLMRHOOTeRQvqKDhJhRSQVaHwyk9P1
      - key: WEAVIATE_PORT
        value: 443 # Utilisez 443 pour HTTPS